### ISSUE TITLE
Request: Ability to configure Huginn's webroot path (i.e., /huginn)

### ISSUE THREAD

**Issue by atkinsj** [huginn/huginn#2325] opened 2018-06-28 06:48 UTC
It would be helpful for more complicated reverse proxy scenarios if we could move Huginn's web console from / to /huginn or some other configurable variable. This allows people to have one host reverse proxy to multiple backend applications.

**Comment by dsander** [comment] 2018-06-28 07:50
Please use the search function before opening new issues. Duplicate of #2301 and #2040. You can always host multiple instances on one domain by using subdomains.

**Closed by dsander** 2018-06-28 07:50 UTC
