### ISSUE TITLE
Website Agent, possible to access prior results for comparison?

### ISSUE THREAD

**Issue by nemosmithasf** [huginn/huginn#2761] opened 2020-04-25 16:58 UTC
For example: if I wanted to set up a `website agent` to monitor prices. I'm hoping to get a email that states `previous price` and `current price`. However, I can't find any option to access the `previous price`.

Does anybody know a way to do this?

**Comment by virtadpt** [comment] 2020-04-25 18:17
Use the Attribute Difference Agent.

**Comment by nemosmithasf** [comment] 2020-04-25 22:45
If I understand the docs correctly, I'll need an `Attribute Difference` agent for each set of `website` monitors I have... I don't think this would scale very well once I increase the number of monitors.

**Comment by virtadpt** [comment] 2020-04-27 00:11
It seems to scale pretty well.  I've got a couple of dozen in my setup these days.

**Comment by nemosmithasf** [comment] 2020-04-27 17:37
I actually mean in terms of manually creating the agents.

Unless I'm mistaken in how to use Huginn, I assume you have to create 2 agents and manually link them for every single "scrape and compare" event. Is that correct?

**Comment by virtadpt** [comment] 2020-04-27 18:16
That is indeed correct.  The nice thing is, once you've set up one pair of agents, you can clone both of them and make minor edits where appropriate.

**Comment by nemosmithasf** [comment] 2020-04-27 19:17
Can you clarify how that would be done? I assumed you would duplicate scenarios, but I just checked and I don’t think there’s such an option.

**Comment by virtadpt** [comment] 2020-04-28 22:09
Sure.  So, if you click on one of your agents, and then go Actions -> Clone agent, you'll see a "Create a new Agent" page that's already been filled in with values from the agent you clicked on.  The name of the agent will be "Whatever the name of your agent is (2)."  You'll want to delete any of the Source and Receivers listed (maybe, depends on what you're doing) and edit any values in the Options block that need it.  Then hit the Save button, and you'll have a duplicate of the agent that's ready to execute.

**Comment by nemosmithasf** [comment] 2020-04-29 10:03
The problem here is that you have to duplicate every agent and relink them manually. So if you had a workflow with 3 steps, it would require configuring it agents per duplication.

Perhaps I should make a feature request for something like a `function` or a `workflow` feature. Basically, a pre-linked set of agents that also takes in some variables?

**Closed** 2020-04-29 10:03 UTC
