### ISSUE TITLE
Growl agent

### ISSUE THREAD

**Issue by International** [huginn/huginn#2018] opened 2017-05-29 11:12 UTC
Hi guys! Long time, no speak :)

I've added 2FA to my gmail last night, and in the morning, I had some failed jobs, cause I've setup my huginn to email me the notifications. I've figured that the easiest way to fix them would be to create a Growl agent, and have that forward my notifications. 

The thing is, I've downloaded gntp-regrowl, but it does not seem to be working. I haven't done any debugging in the python script, but I've noticed this behaviour:

* `gtnp-regrowl` receives messages, but does not seem to take any action
* if I stop `gntp-regrowl` , and have the jobs working in the background, `gntp-regrowl` cannot start, because it says the port is already taken. Doing a `lsof` with port 23093 IIRC, tells me that huginn's job processor is listening on that port
* the ruby gem responsible for sending the notifications to regrowl seems to be hardcoded to work just with port `23093`

Can anyone share the steps you've taken to get growl working? For the time being, I went with a workaround:

* created a POST agent, that is the terminal agent
* implemented a small http server that processes the received events
* call `terminal-notifier` myself

I imagine that more or less, that should be the same functionality that the growl agent provides.

**Comment by dsander** [comment] 2017-05-30 18:50
I have never used that Agent, it sounds surprising that the agent is opening a socket server on this port. I would assume it tries to connect to that port and send the notification to the growl server.

**Comment by tortoo** [comment] 2017-07-25 02:16
I can't also make the growl agent working. @dsander 

{
  "growl_server": "192.168.1.102",
  "growl_password": "",
  "growl_app_name": "HuginnGrowl",
  "growl_notification_name": "Notification",
  "expected_receive_period_in_days": "2"
}

Error Backtrace

                        execution expired (Delayed::Worker.max_run_time is only 120 seconds)
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl/gntp.rb:233:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl/gntp.rb:233:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl/gntp.rb:233:in `connect'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl/gntp.rb:535:in `send'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl/gntp.rb:521:in `register'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl.rb:308:in `notify_gntp'
/app/vendor/bundle/ruby/2.3.0/gems/ruby-growl-4.1/lib/ruby-growl.rb:290:in `notify'
/app/app/models/agents/growl_agent.rb:47:in `notify_growl'
/app/app/models/agents/growl_agent.rb:57:in `block in receive'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/app/app/models/agents/growl_agent.rb:52:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'

I set the Maximum runtime to 30 minutes in .env file, but the Error Backtrace was also showing  that is only 120 seconds.
# Maximum runtime of background jobs in minutes
DELAYED_JOB_MAX_RUNTIME=30

**Comment by dsander** [comment] 2017-07-25 08:12
@tortoo That error happens because Huginn can not connect to the growl server, can you connect from the server that runs Huginn via telnet? `telnet 192.168.1.102 23053`

Depending on how you run Huginn, you need to reexport the services on production or restart foreman to apply changes made to `.env`.

**Comment by tortoo** [comment] 2017-07-26 05:47
@dsander I tried telnet, it's OK. 

$ telnet 192.168.1.102 23053
Trying 192.168.1.102...
Connected to 192.168.1.102.
Escape character is '^]'.
Connection closed by foreign host.

Is that means I should increase the Maximum runtime? I searched a lot but didn't find the command how to reexport the services on production or restart foreman.🙈 I use Mac OS  and my huginn was deployed on heroku. Thank you very much for helping!

**Comment by dsander** [comment] 2017-07-26 08:41
I see, on Heroku the `.env` file is not used if you want to modify any configuration variable it has to be done via the Heroku CLI: `heroku config:set DELAYED_JOB_MAX_RUNTIME=30`

Accessing your local network from Heroku will not work, you would need to add a port forward to your router and set up a dynamic DNS server to be able to access your computer from the internet.

**Comment by tortoo** [comment] 2017-07-26 10:13
I have set up the growl sever(gntp) with pip and  tested with the following command and received the growl notification immediately, does that mean I still need to set up a dynamic DNS server? @dsander 

$ python -m gntp.notifier
INFO:__main__:Sending registration to localhost:23053
INFO:__main__:Sending notification [Message] to localhost:23053

**Comment by dsander** [comment] 2017-07-27 09:10
I think so yes. The growl server is running on you local machine and Huginn is running on Heroku, right? 
If your internet connection is going through a router that router will block incoming connection by default. So you need to set up a port forwarding on the router which sends external connections on port `23053` to your local computer. The IP to use for the `GrowlAgent` should also be your external IP address: http://canihazip.com/

**Comment by tortoo** [comment] 2017-07-28 00:54
I understand completely! Thank you very much! @dsander

**Comment by tortoo** [comment] 2017-07-29 06:51
Hi desander, I'm back again😹. I got a third party service and a fixed IP address, now the Growl Agent goes very well. But if I want the notification to jump to the URL after clicking, besides the message and subject field, what else  I should add ? Growl has callback url function but how to use it on Growl Agent? Thanks again! @desander

**Comment by dsander** [comment] 2017-07-30 18:48
Nice, glad to hear that it is working now. The Agent currently only supports setting the `subject` and `message`. I found this [note](https://github.com/drbrain/ruby-growl/blob/master/lib/ruby-growl/gntp.rb#L255-L257) in the source code of the Growl client library Huginn uses. Does setting a `callback_url` work when you are using a different client to send the notification?

**Comment by tortoo** [comment] 2017-07-31 01:40
My callback_url can only work on this APP Simon![image](http://i.imgur.com/nv7oZn1.jpg), Growl and it's notification jumping by clicking is the inside function by itself.  There's a callback APP in  My Growl notification APP list![image](http://i.imgur.com/qtjzuuD.jpg),but I don't know if it was set by Simon. I never set the callback_url and don't know how since the gntp official installation didn't mention that[GNTP](https://github.com/kfdm/gntp)[GNTP Basics](https://pythonhosted.org/gntp/). And it seems not to be working except Simon. If the commands was given, I'll do it.😹

**Comment by dsander** [comment] 2017-07-31 08:38
Hmm I wanted to try it on OSX but could not find a free Growl app. We could add support for setting a callback URL in the Agent but it would be nice to know if there are Growl application that support it.

Besides Growl I can recommend the `PushbulletAgent`, they have browser plugins which allow to open received URL directly.

**Comment by tortoo** [comment] 2017-07-31 09:35
Grow is here [Growl ](http://uploaded.net/file/4sh138t0). Simon is here [Simon](http://uploaded.net/file/dr45u3gr). Other application supported by Growl  like Gmail or Mail of Mac can send notification with Growl [Gmail or Mail](http://growl.info/applications.php?cat=Email),but I didn't try this. If you need some other applications supported by Growl, tell me, I think I can try to find for you 😹. The great reason I use Growl is that it can  speak out the notification when my screen was shut  automatically, pushbullet can't do this. If callback url can be set to work, it'll be very great! Thanks!

**Comment by dsander** [comment] 2017-07-31 20:24
@tortoo Thanks, setting a `callback_url` works well with the Growl app. I created a pull request to add support for a few new options.

**Comment by tortoo** [comment] 2017-08-01 06:59
So good job and so fast! Thank you very much! But I think I haven't made this work yet, because I find that my Simon is jumping on clicking by Mac's default notification even though the Growl notification is also working at the same time. It seems that I should also install another plugin named growlnotify. The problem is I don't how to set it to work. I'm still searching for this. 😹

**Comment by tortoo** [comment] 2017-08-01 09:14
I'm so confused that if the growlnotify is needed if I only need jumping to url by clicking. The official explanation is following:

Callbacks
Callbacks are sent back to the sending application when an action is taken in response to a notification. Callbacks are formatted similar to responses, but the only supported <messagetype> is:

-CALLBACK

If the NOTIFY message contains the 'Notification-Callback-Context' and 'Notification-Callback-Context-Type' headers, the notification system will send a callback when a callback condition is met. Callback conditions are:

The notification is clicked by the end user
The notification is closed explicitly by the end user
The notification times out
Only ONE of these three conditions - whichever occurs first - will trigger a callback for any given notification.

A callback may be sent either via the TCP socket which made the connection initially or to an alternative URL specified in the 'Notification-Callback-Target' header of the request.

Socket Callbacks
If the NOTIFY request contains the 'Notification-Callback-Context' and 'Notification-Callback-Context-Type' headers *and* the 'Notification-Callback-Target' header is not specified, then the receiver will maintain the TCP connection until a callback condition occurs. The callback MUST contain the following headers:

Application-Name: <string>
Required - The name of the application that sent the original request

Notification-ID: <string>
Required - The value of the 'Notification-ID' header from the original request

Notification-Callback-Result: <string>
Required - [CLICKED|CLOSED|TIMEDOUT] | [CLICK|CLOSE|TIMEOUT]

Notification-Callback-Timestamp: <date>
Required - The date and time the callback occurred

Notification-Callback-Context: <string>
Required - The value of the 'Notification-Callback-Context' header from the original request

Notification-Callback-Context-Type: <string>
Required - The value of the 'Notification-Callback-Context-Type' header from the original request

Callbacks may also contain the generic headers defined in the 'Responses' section, as well as custom headers as defined in the 'Custom Headers' portion of the 'Requests' section above.

URL Callbacks
If a URL is specified via the 'Notification-Callback-Target' header, the TCP connection will be closed once a notification is received. When a notification is clicked, the callback url will be opened in the user's default browser. Unlike socket callbacks, URL callbacks are only triggered if the notification is clicked (CLICK|CLICKED), not for CLOSE|CLOSED or TIMEOUT|TIMEDOUT actions. The callback url is not modified in any way, so if notification information is required (such as Notification ID), it must be specified as part of the callback URL in the request.

Notes:

A notification can forgo callback notifications by omitting all of the 'Notification-Callback-*' headers.


My Event formatting event is following:
{
  "instructions": {
    "message": "{{description}}
    "subject": "{{title}}",
    "callback_url": "{{url}}"
  },
  "matchers": [

  ],
  "mode": "merge"
}

And my Growl Agent is following:
{
  "growl_server": "x.x.x.x",
  "growl_password": "",
  "growl_app_name": "HuginnGrowl",
  "growl_notification_name": "Notification",
  "expected_receive_period_in_days": "2",
  "callback_url": "{{callback_url}}"
}

But when I click the notification it can't work.

**Comment by dsander** [comment] 2017-08-01 17:36
Did you upgrade your Huginn installation to use my branch? I just merged the PR, now you can follow the official [upgrade instructions](https://github.com/huginn/huginn/blob/master/doc/heroku/update.md) for Heroku.

**Comment by tortoo** [comment] 2017-08-02 02:43
@dsander Sorry I never know about this upgrading🙈. After doing that, it seems to be some problems. What should I do?

$ git fetch origin
remote: Counting objects: 624, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 624 (delta 384), reused 383 (delta 378), pack-reused 231
Receiving objects: 100% (624/624), 140.61 KiB | 63.00 KiB/s, done.
Resolving deltas: 100% (465/465), completed with 161 local objects.
From https://github.com/cantino/huginn
   fbb7df32..af5da3a1  master                  -> origin/master
 * [new branch]        configurable_search_url -> origin/configurable_search_url
$ git merge origin/master
Updating fbb7df32..af5da3a1
error: Your local changes to the following files would be overwritten by merge:
	Gemfile.lock
Please commit your changes or stash them before you merge.
Aborting
$ git push -f heroku master
Everything up-to-date
$ heroku run rake db:migrate
Running rake db:migrate on ⬢ XXX... up, run.7441 (Free)
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by dsander** [comment] 2017-08-02 08:33
Looks like you have changes in your local `Gemfile.lock` it it probably best to revert it to the original version with:
```
git checkout Gemfile.lock
```
after that
```
git merge origin/master
git push -f heroku master
heroku run rake db:migrate
```

should wrok.

**Comment by tortoo** [comment] 2017-08-03 05:26
It works so perfectly!😸 You are very great! I'm so appreciate! @dsander

**Comment by dsander** [comment] 2017-08-03 17:36
Nice, glad the changes work for you. 😄

**Closed by dsander** 2017-08-03 17:36 UTC
