### ISSUE TITLE
Installation  fails on Raspberry Pi 3: libv8 not supported (therubyracer)

### ISSUE THREAD

**Issue by LorenzoAncora** [huginn/huginn#2372] opened 2018-09-14 09:35 UTC
Hi,
I receive this error when installing Huginn on `GNU/Linux 4.17.0-3-arm64 SMP Debian 4.17.17-1 (2018-08-18) aarch64`. When installing therubyracer i receive this error:

```
Compiling v8 for x64
Using python 2.7.15+
Using compiler: c++ (GCC version 8.2.0)
Beginning compilation. This will take some time.
Building v8 with env CXX=c++ LINK=c++  /usr/bin/make x64.release ARFLAGS.target=crs werror=no
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=x64 \
              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
make[1]: ingresso nella directory "/var/lib/gems/2.5.0/gems/libv8-3.16.14.19/vendor/v8/out"
  CXX(target) /var/lib/gems/2.5.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
In file included from ../src/allocation.h:31,
                 from ../src/allocation.cc:28:
../src/globals.h:90:2: error: #error Host architecture was not detected as supported by v8
 #error Host architecture was not detected as supported by v8
  ^~~~~
../src/globals.h:116:2: error: #error Target architecture x64 is only supported on x64 host
 #error Target architecture x64 is only supported on x64 host
  ^~~~~
make[1]: *** [tools/gyp/preparser_lib.target.x64.mk:108: /var/lib/gems/2.5.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o] Error 1
make[1]: uscita dalla directory "/var/lib/gems/2.5.0/gems/libv8-3.16.14.19/vendor/v8/out"
make: *** [Makefile:195: x64.release] Error 2
/var/lib/gems/2.5.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/var/lib/gems/2.5.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /var/lib/gems/2.5.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `each'
        from /var/lib/gems/2.5.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `verify_installation!'
        from /var/lib/gems/2.5.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

I suspect that it fails to detect the correct architecture.
Debian already offers a precompiled version of libv8 but Huginn does not fallback to it.

**Comment by dsander** [comment] 2018-09-16 11:09
Duplicate of a few issues. Getting Huginn to run on a Raspberry has always been problematic.

https://github.com/huginn/huginn/issues/2299
https://github.com/huginn/huginn/issues/1586

**Closed by dsander** 2018-09-16 11:09 UTC

**Comment by LorenzoAncora** [comment] 2018-09-16 17:49
> Duplicate of a few issues. Getting Huginn to run on a Raspberry has always been problematic.

@dsander  this is not a duplicate: I am not using 32-bit Raspbian but the Debian ARMv8 64-bit  environment. My architecture is the native _aarch64_ for the ARMv8 processor of Raspberry Pi 3 B.

```
arm_control=0x200
kernel=vmlinuz-4.17.0-3-arm64
```

**Comment by dsander** [comment] 2018-09-17 07:50
Sorry I missed the real original issue https://github.com/huginn/huginn/issues/1586.

The others are just related to raspberry installations in general.
