### ISSUE TITLE
events_order problem. On the RSS reader, the order of the articles is still reversed.

### ISSUE THREAD

**Issue by sanyejyo** [huginn/huginn#2492] opened 2019-02-14 05:12 UTC
I have encountered the same problem, I tried it according to his statement. After using his method, open the URL link in the Summary on the browser, and the order of the articles is normal. However, using the rss reader to subscribe to the URL link in Summary, the order of the articles seen on the reader is still reversed.

This is a link to a problem like me. [https://github.com/huginn/huginn/issues/2409](https://github.com/huginn/huginn/issues/2409)

This is my code.
```
{
"secrets": [
"huanjiang"
],
"expected_receive_period_in_days": "2",
"template": {
"title": "tongzhi",
"description": "wu",
"item": {
"title": "{{title}}",
"description": "{{quanwen}}",
"link": "{{url}}",
}
},
"events_order": [
"{{date_published}}",
"time",
"descending"
]
}
```

**Comment by dsander** [comment] 2019-02-14 09:00
Is the ordering of elements in your RSS reader consistent with the `pubDate` field of the feed? I assume the reader uses that field instead of relying on the order in the XML. Per default `pubDate` is set to the creation time of the Event, but you can override it in the item `template`.

**Comment by sanyejyo** [comment] 2019-02-14 09:13
> RSS阅读器中元素的排序是否与`pubDate`Feed字段一致？我假设读者使用该字段而不是依赖于XML中的顺序。默认`pubDate`设置为事件的创建时间，但您可以在项目中覆盖它`template`。

Hello, most rss readers are sorted by default using pubDate. How should I modify my template?

**Comment by sanyejyo** [comment] 2019-02-14 09:20
> Is the ordering of elements in your RSS reader consistent with the `pubDate` field of the feed? I assume the reader uses that field instead of relying on the order in the XML. Per default `pubDate` is set to the creation time of the Event, but you can override it in the item `template`.

Hello, most rss readers are sorted by default using pubDate. How should I modify my template?

**Comment by dsander** [comment] 2019-02-15 08:28
You can add the `pubDate`  to the `item` section of the Agent configuration, does the Website you are extracting the information from have any date associated with the data?
```json
"item": {
  "title": "{{title}}",
  "description": "{{quanwen}}",
  "link": "{{url}}",
  "pubDate": "1970-01-01 00:00:00"
}
```

**Comment by sanyejyo** [comment] 2019-02-15 09:17
> 

> 

> 

>

**Comment by sanyejyo** [comment] 2019-02-15 10:18
thank you . It works! According to your suggestion, I tried it and it works fine on the rss reader.
This is the normal working DataOutputAgent:

{
"secrets": [
"huanjiang"
],
"expected_receive_period_in_days": "2",
"template": {
"title": "tongzhi",
"description": "wu",
"item": {
"title": "{{title}}",
"description": "{{quanwen}}",
"link": "{{url}}",
"pubDate":"1970-01- 01 00:00:00"
}
},
"events_order": [
"{{pubDate}}",
"time",
"true"
]
}

Sorry, I just used huginn for a few days.  I can extract the date associated with the data from the website. The date is extracted from the text() format. The format of the extracted date is not like this 1970-01-01 00:00:00 or 1970-01-01. For example, the extracted date format is like this (1970-01-01) or 2019年2月13日，Dates like this format are passed directly to pubDate, can they be identified?
Or how to change the date format on Huginn. Can you give me some advice on this knowledge?
And I think this method will be very troublesome.
Thank you for your reply.

**Comment by dsander** [comment] 2019-02-16 08:49
You can use the [liquid date filter](https://shopify.github.io/liquid/filters/date/) to convert a string to a well formatted date: `{{ "1970-01-01" | date: "%FT%TZ" }}`. The problem is that it only works with strings are already in a "common" date formats (under the hood it uses Rubys [Time.parse](https://ruby-doc.org/stdlib-2.1.1/libdoc/time/rdoc/Time.html#method-c-parse) function. In the case `(1970-01-01)` you only need to get rid of the parentheses: `{{ "(1970-01-01)" | replace "(", "" | replace ")", "" | date: "%FT%TZ" }}`.

For some reason a similar approach does not work for the Chinese characters, i tried replacing them with `-` but for some reason it is unable to locate the characters `{{ "2019年2月13日" | replace "年", "-" | replace "月", "-" | replace "日", "" | date: "%FT%TZ" }}`, keeps the date in the original format 😞

**Comment by sanyejyo** [comment] 2019-02-16 11:18
Thanks a million sir! Thank you very much for your kind help.
The recognition of Chinese characters may involve unicode coding, and I am still a newbie.
Have a nice day！

**Comment by dsander** [comment] 2019-02-18 09:36
I am closing this issue. Please feel free to reopen if you need further assistance!

**Closed by dsander** 2019-02-18 09:36 UTC
